apiVersion: apps/v1
kind: Deployment
metadata:
    name: abapp-deployment
    labels:
        app: abapp-label
spec:
    replicas: 1
    selector:
        matchLabels:
            app: abapp-label
    template:
        metadata:
            labels:
                app: abapp-label
        spec:
        - name: abapp                                                     # it should have '-' in the beginning
          image: addressbook:V1.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8082                                            # it should have '-' in the beginning
---
apiVersion: v1
kind: Service
metadata:
    name: abapp-service
spec:
    selector:
        app: abapp-label
    ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
type: NodePort
